version: "3.5"
services:
    mysql:
        image: mysql:8.0.26
        container_name: mdshop-api-mysql
        working_dir: /application
        volumes:
            - .:/application
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - mdshop-net

    php-fpm:
        image: eclimov/mdshop-api:latest
        container_name: mdshop-api-php-fpm
        working_dir: /application
        volumes:
            - .:/application
        #            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini
        networks:
            - mdshop-net

    webserver:
        image: nginx:alpine
        container_name: mdshop-api-webserver
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - mysql
            - php-fpm
        ports:
            - 81:80
        networks:
            - mdshop-net
#TODO: remove the following?
#networks:
#    mdshop-net:
#        external: true
networks:
    mdshop-net:
        name: mdshop-net
        driver: bridge
