version: "3.5"
services:
    php-fpm:
        build:
            context: .
            dockerfile: docker/ci/php-fpm/Dockerfile
        container_name: mdshop-api-php-fpm
        environment:
            - APP_ENV=${APP_ENV}
            - APP_SECRET=${APP_SECRET}
