version: 2
jobs:
  deploy:
    working_directory: ~/eclimov/mdshop-api
    docker:
      - image: docker:18.05.0-ce-git
    steps:
      - deploy:
          name: Deploy application to Digital Ocean
          command: |
            ssh -o "StrictHostKeyChecking no" $DEPLOY_USER@$DEPLOY_HOST bash -c "
                cd /root
                git clone https://github.com/eclimov/mdshop-api ; cd mdshop-api
                git reset --hard
                git pull
                docker-compose stop
                export MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
                export MYSQL_DATABASE=$MYSQL_DATABASE
                export MYSQL_USER=$MYSQL_USER
                export MYSQL_PASSWORD=$MYSQL_PASSWORD
                export MYSQL_CONTAINER_NAME=$MYSQL_CONTAINER_NAME
                export DATABASE_URL=mysql://$MYSQL_USER:$MYSQL_PASSWORD@$MYSQL_CONTAINER_NAME/$MYSQL_DATABASE
                export JWT_PASSPHRASE=$JWT_PASSPHRASE
                docker-compose up -d --build --force-recreate
                docker-compose exec -T php-fpm bin/console doctrine:migrations:migrate -n
                docker container prune -f
                docker image prune -f
                docker network prune -f
                docker volume prune -f"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          context: mdshop
          filters:
            branches:
              only: master
